### ISSUE TITLE
Webkit version incorrect for Flathub build

### ISSUE THREAD

**Issue by babluboy** [flathub/com.github.babluboy.bookworm#4]
@nedrichards Hi, need your help in fixing the flathub build for the latest release of bookworm.
I can see from the [logs](https://flathub.org/builds/#/builders/6/builds/1694) that the code did not build due to errors for webkit
```
/run/build/bookworm/src/window.vala:363.77-363.111: error: The name `from_gaction' does not exist in the context of `WebKit.ContextMenuItem'
WebKit.ContextMenuItem pageContextMenuItemWordMeaning = new WebKit.ContextMenuItem.from_gaction (
```
the from_gaction method exists in webkit from version [[ Version ( since = "2.18" ) ]](https://valadoc.org/webkit2gtk-4.0/WebKit.ContextMenuItem.ContextMenuItem.from_gaction.html)

Also the latest release did not add this code, so I'm wondering how it succeeded for the last flatpak build.

**Comment by TingPing** [comment]
WebkitGtk 2.18.6 is in the 3.26 sdk.

**Comment by babluboy** [comment]
@TingPing Many thanks for the help - I updated the json to mention 3.26 SDK and the build went [fine](https://flathub.org/builds/#/builders/1/builds/2089). I can see the Bookworm icon updated on flathub.
