### ISSUE TITLE
How to package python for Flatpak Bookworm packaging

### ISSUE THREAD

**Issue by babluboy** [flathub/com.github.babluboy.bookworm#8]
@TingPing Need some guidance on how to make python available for Bookworm's Flatpak packaging.
This is how the python executable is called and it works as Elementary OS has the python executable available on the correct path to be invoked from Vala.

1. Vala code calls a python script using the Process.spawn_async_with_pipes ([here](https://github.com/babluboy/bookworm/blob/b8811eda9946e6069f7823dc791dd6c26669ba46/src/mobiReader.vala#L104))

2. The mobi script being called starts with "#!/usr/bin/env python2" ([here](https://github.com/babluboy/bookworm/blob/b8811eda9946e6069f7823dc791dd6c26669ba46/data/scripts/mobi_lib/mobi_unpack.py#L1))

The above arrangement works for all distributions with python installed, so can I package python in the flatpak manifest so the above code does not need to change.
I found some examples of how to package python for Flatpak here:
https://www.loganasherjones.com/2018/05/using-flatpak-with-python/

Thanks in advance for your guidance.

**Comment by TingPing** [comment]
You can use the Python 2 from here: https://github.com/flathub/shared-modules

**Comment by babluboy** [comment]
@tingping many thanks for the suggestion. Is there an example you can point me at?

How do I mention this in the manifest:
 git submodule add https://github.com/flathub/shared-modules.git

What should I mention as foo while adding the following to my json 

"modules": [
  "shared-modules/SDL/SDL-1.2.15.json",
  {
    "name": "foo"
  }
]

**Comment by TingPing** [comment]
Not sure how that isn't clear:

`"shared-modules/python2.7/python-2.7.15.json"`

**Comment by TingPing** [comment]
`foo` is a random example and just whatever you currently have

**Comment by babluboy** [comment]
Thanks...just a noob at Flatpack, apologies. Will try this out. Appreciate your help
